import type { Ad } from "./types"

export const mockAds: Ad[] = [
  // Vehicles
  {
    id: "1",
    title: "Volkswagen Golf 7 2.0 TDI",
    description:
      "Одлично зачуван Golf 7 со сервисна книшка. Редовно сервисиран кај овластен дилер. Без никакви дефекти.",
    price: 12500,
    category: "vehicles",
    location: "Скопје",
    images: ["/volkswagen-golf-7-silver-car.jpg"],
    createdAt: "2026-01-10T10:00:00Z",
    userId: "1",
    userName: "Марко П.",
    brand: "Volkswagen",
    model: "Golf 7",
    year: 2018,
    mileage: 95000,
    fuelType: "Дизел",
  },
  {
    id: "2",
    title: "BMW 320d F30",
    description: "BMW во одлична состојба. Целосна сервисна историја. Нови гуми и кочници.",
    price: 18000,
    category: "vehicles",
    location: "Битола",
    images: ["/bmw-320d-black-sedan.jpg"],
    createdAt: "2026-01-09T15:30:00Z",
    userId: "2",
    userName: "Иван К.",
    brand: "BMW",
    model: "320d",
    year: 2016,
    mileage: 120000,
    fuelType: "Дизел",
  },
  {
    id: "3",
    title: "Mercedes C220 AMG пакет",
    description: "Mercedes C класа со AMG пакет. Кожен ентериер, навигација, LED фарови.",
    price: 25000,
    category: "vehicles",
    location: "Скопје",
    images: ["/mercedes-c-class-white-amg.jpg"],
    createdAt: "2026-01-08T12:00:00Z",
    userId: "3",
    userName: "Петар С.",
    brand: "Mercedes",
    model: "C220",
    year: 2019,
    mileage: 65000,
    fuelType: "Дизел",
  },
  {
    id: "4",
    title: "Audi A4 Quattro",
    description: "Audi A4 со Quattro погон. Идеален за зима. Целосна опрема.",
    price: 16500,
    category: "vehicles",
    location: "Тетово",
    images: ["/audi-a4-grey-quattro.jpg"],
    createdAt: "2026-01-07T09:00:00Z",
    userId: "4",
    userName: "Александар М.",
    brand: "Audi",
    model: "A4",
    year: 2017,
    mileage: 110000,
    fuelType: "Дизел",
  },
  {
    id: "9",
    title: "Toyota Corolla Hybrid",
    description: "Економично хибридно возило со мала потрошувачка. Идеално за градска возња.",
    price: 22000,
    category: "vehicles",
    location: "Скопје",
    images: ["/white-toyota-corolla-hybrid.png"],
    createdAt: "2026-01-12T08:00:00Z",
    userId: "9",
    userName: "Никола Т.",
    brand: "Toyota",
    model: "Corolla Hybrid",
    year: 2021,
    mileage: 35000,
    fuelType: "Хибрид",
  },
  {
    id: "10",
    title: "Opel Astra K",
    description: "Opel Astra во одлична состојба. Сервисирано, нови гуми. Еден сопственик.",
    price: 11000,
    category: "vehicles",
    location: "Куманово",
    images: ["/opel-astra-k-red-hatchback.jpg"],
    createdAt: "2026-01-11T14:00:00Z",
    userId: "10",
    userName: "Дарко С.",
    brand: "Opel",
    model: "Astra K",
    year: 2017,
    mileage: 89000,
    fuelType: "Бензин",
  },

  // Real Estate
  {
    id: "5",
    title: "Тросоен стан во Центар",
    description: "Реновиран тросоен стан во строгиот центар на Скопје. Близу до сите содржини. Паркинг место вклучено.",
    price: 95000,
    category: "real-estate",
    location: "Скопје",
    images: ["/apartment-interior-1.png"],
    createdAt: "2026-01-11T08:00:00Z",
    userId: "5",
    userName: "Ана Т.",
    area: 85,
    rooms: 3,
    propertyType: "Стан",
  },
  {
    id: "6",
    title: "Двособен стан Аеродром",
    description: "Нов двособен стан во населба Аеродром. Лифт, подрум, балкон со поглед.",
    price: 65000,
    category: "real-estate",
    location: "Скопје",
    images: ["/cozy-apartment-bedroom-modern.jpg"],
    createdAt: "2026-01-10T14:00:00Z",
    userId: "6",
    userName: "Горан Н.",
    area: 55,
    rooms: 2,
    propertyType: "Стан",
  },
  {
    id: "7",
    title: "Куќа со двор во Охрид",
    description: "Прекрасна куќа со голем двор во близина на Охридското езеро. Три спални, две бањи.",
    price: 180000,
    category: "real-estate",
    location: "Охрид",
    images: ["/traditional-macedonian-house-with-garden.jpg"],
    createdAt: "2026-01-09T11:00:00Z",
    userId: "7",
    userName: "Марија Д.",
    area: 150,
    rooms: 5,
    propertyType: "Куќа",
  },
  {
    id: "8",
    title: "Деловен простор Центар",
    description: "Деловен простор на одлична локација. Погоден за канцеларии или продавница.",
    price: 120000,
    category: "real-estate",
    location: "Битола",
    images: ["/modern-office-interior-space.jpg"],
    createdAt: "2026-01-08T16:00:00Z",
    userId: "8",
    userName: "Стефан Р.",
    area: 100,
    rooms: 4,
    propertyType: "Деловен простор",
  },

  // Electronics
  {
    id: "21",
    title: "iPhone 15 Pro Max 256GB",
    description: "Нов iPhone 15 Pro Max, запечатен во кутија. Гаранција од овластен дистрибутер.",
    price: 1200,
    category: "electronics",
    location: "Скопје",
    images: ["/iphone-15-pro-max.png"],
    createdAt: "2026-01-12T09:00:00Z",
    userId: "21",
    userName: "Дејан М.",
    brand: "Apple",
    model: "iPhone 15 Pro Max",
    condition: "Ново",
  },
  {
    id: "22",
    title: "MacBook Pro M3 14 инчи",
    description: "MacBook Pro со M3 чип, 16GB RAM, 512GB SSD. Користен 3 месеци, во одлична состојба.",
    price: 1800,
    category: "electronics",
    location: "Скопје",
    images: ["/macbook-pro-laptop-silver.jpg"],
    createdAt: "2026-01-11T10:00:00Z",
    userId: "22",
    userName: "Мартин К.",
    brand: "Apple",
    model: "MacBook Pro M3",
    condition: "Користено - како ново",
  },
  {
    id: "23",
    title: "Samsung Galaxy S24 Ultra",
    description: "Samsung Galaxy S24 Ultra, 256GB, црна боја. Со оригинален полнач и кутија.",
    price: 950,
    category: "electronics",
    location: "Битола",
    images: ["/samsung-galaxy-s24-ultra-phone.jpg"],
    createdAt: "2026-01-10T15:00:00Z",
    userId: "23",
    userName: "Филип Н.",
    brand: "Samsung",
    model: "Galaxy S24 Ultra",
    condition: "Користено - како ново",
  },
  {
    id: "24",
    title: "PlayStation 5 со 2 контролери",
    description: "PlayStation 5 Disc верзија со два оригинални контролери. Вклучени 3 игри.",
    price: 450,
    category: "electronics",
    location: "Тетово",
    images: ["/playstation-5-gaming-console.jpg"],
    createdAt: "2026-01-09T12:00:00Z",
    userId: "24",
    userName: "Бојан С.",
    brand: "Sony",
    model: "PlayStation 5",
    condition: "Користено - добра состојба",
  },
  {
    id: "25",
    title: "Gaming PC RTX 4070",
    description: "Gaming компјутер со RTX 4070, Ryzen 7 5800X, 32GB RAM, 1TB NVMe SSD. Идеален за gaming.",
    price: 1100,
    category: "electronics",
    location: "Скопје",
    images: ["/gaming-pc-rgb-lights.jpg"],
    createdAt: "2026-01-08T14:00:00Z",
    userId: "25",
    userName: "Никола Р.",
    brand: "Custom",
    model: "Gaming PC",
    condition: "Користено - добра состојба",
  },

  // Jobs
  {
    id: "26",
    title: "Senior Frontend Developer",
    description: "Баране искусен Frontend developer со познавање на React, TypeScript. Работа од дома можна.",
    price: 0,
    category: "jobs",
    location: "Скопје",
    images: ["/modern-office-workspace.png"],
    createdAt: "2026-01-12T08:00:00Z",
    userId: "26",
    userName: "IT Solutions",
    jobType: "Полно работно време",
    salary: "80.000 - 120.000 МКД",
  },
  {
    id: "27",
    title: "Продавач/ка во бутик",
    description: "Потребен продавач/ка за бутик за облека во центар на Скопје. Работно време од 10-18ч.",
    price: 0,
    category: "jobs",
    location: "Скопје",
    images: ["/clothing-boutique-store.jpg"],
    createdAt: "2026-01-11T11:00:00Z",
    userId: "27",
    userName: "Fashion Store",
    jobType: "Полно работно време",
    salary: "25.000 - 30.000 МКД",
  },
  {
    id: "28",
    title: "Келнер/ка за ресторан",
    description: "Ресторан во Охрид бара келнер/ка за летна сезона. Можност за сместување.",
    price: 0,
    category: "jobs",
    location: "Охрид",
    images: ["/restaurant-waiter-serving.jpg"],
    createdAt: "2026-01-10T09:00:00Z",
    userId: "28",
    userName: "Езерски Ресторан",
    jobType: "Полно работно време",
    salary: "35.000 - 45.000 МКД + бакшиш",
  },
  {
    id: "29",
    title: "Возач на камион C+E",
    description: "Транспортна компанија бара возач со C+E категорија за меѓународен превоз.",
    price: 0,
    category: "jobs",
    location: "Куманово",
    images: ["/truck-driver-highway.jpg"],
    createdAt: "2026-01-09T14:00:00Z",
    userId: "29",
    userName: "Trans Logistics",
    jobType: "Полно работно време",
    salary: "60.000 - 80.000 МКД",
  },

  // Services
  {
    id: "30",
    title: "Молерски услуги",
    description: "Професионални молерски услуги. Внатрешно и надворешно молерисување. Брзо и квалитетно.",
    price: 150,
    category: "services",
    location: "Скопје",
    images: ["/painter-painting-wall.png"],
    createdAt: "2026-01-12T10:00:00Z",
    userId: "30",
    userName: "Боби Молер",
    serviceType: "Градежништво",
  },
  {
    id: "31",
    title: "Чистење на станови",
    description: "Темелно чистење на станови и куќи. Со сопствена опрема и средства за чистење.",
    price: 25,
    category: "services",
    location: "Скопје",
    images: ["/house-cleaning-service.png"],
    createdAt: "2026-01-11T13:00:00Z",
    userId: "31",
    userName: "Clean Home",
    serviceType: "Чистење",
  },
  {
    id: "32",
    title: "Приватни часови по математика",
    description: "Дипломиран математичар нуди приватни часови за основно и средно образование.",
    price: 400,
    category: "services",
    location: "Битола",
    images: ["/math-tutoring-student.jpg"],
    createdAt: "2026-01-10T16:00:00Z",
    userId: "32",
    userName: "Проф. Јован",
    serviceType: "Настава",
  },
  {
    id: "33",
    title: "Селидби и транспорт",
    description: "Селидби низ цела Македонија. Обезбедуваме работници и транспортно возило.",
    price: 50,
    category: "services",
    location: "Скопје",
    images: ["/moving-truck-boxes.jpg"],
    createdAt: "2026-01-09T11:00:00Z",
    userId: "33",
    userName: "Move Fast",
    serviceType: "Превоз",
  },

  // Furniture
  {
    id: "34",
    title: "Кожна гарнитура 3+2+1",
    description: "Квалитетна кожна гарнитура во одлична состојба. Боја: кафена. Димензии по договор.",
    price: 800,
    category: "furniture",
    location: "Скопје",
    images: ["/leather-sofa-set-brown.jpg"],
    createdAt: "2026-01-12T11:00:00Z",
    userId: "34",
    userName: "Марија К.",
    furnitureType: "Софи и гарнитури",
    condition: "Користено - добра состојба",
  },
  {
    id: "35",
    title: "Трпезариска маса со 6 столици",
    description: "Дрвена трпезариска маса со 6 столици. Масивен дрво, рачна изработка.",
    price: 450,
    category: "furniture",
    location: "Тетово",
    images: ["/dining-table-wooden-chairs.jpg"],
    createdAt: "2026-01-11T14:00:00Z",
    userId: "35",
    userName: "Ахмед С.",
    furnitureType: "Маси и столици",
    condition: "Користено - добра состојба",
  },
  {
    id: "36",
    title: "Двокреветна спална гарнитура",
    description: "Комплетна спална гарнитура: кревет 160x200, два ноќни шкафчиња, гардероба.",
    price: 650,
    category: "furniture",
    location: "Охрид",
    images: ["/bedroom-furniture-set-modern.jpg"],
    createdAt: "2026-01-10T10:00:00Z",
    userId: "36",
    userName: "Емилија Т.",
    furnitureType: "Кревети",
    condition: "Користено - како ново",
  },
  {
    id: "37",
    title: "Канцелариска маса и стол",
    description: "Ергономска канцелариска маса со gaming стол. Идеално за работа од дома.",
    price: 300,
    category: "furniture",
    location: "Скопје",
    images: ["/office-desk-gaming-chair.jpg"],
    createdAt: "2026-01-09T15:00:00Z",
    userId: "37",
    userName: "Виктор П.",
    furnitureType: "Канцелариски",
    condition: "Користено - добра состојба",
  },
]
